name: Run Builds
on:
  push:
    branches: ci-test
    paths-ignore:
      - "*.md"
jobs:
  build:
    name: build on runner
    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run container
        run: |
          mkdir dist && chmod 770 Intermediate
          mkdir Intermediate && chmod 770 Intermediate
          mkdir Binaries && chmod 770 Binaries
          mkdir Build && chmod 770 Build
          mkdir Saved && chmod 770 Saved
          docker run -v$PWD:/tmp/project -v$PWD/dist:/tmp/dist mirage-unreal-builder
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          file: dist/Android/*
          tag: ${{ github.ref }}
